name: Weekly Code Quality Report

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:  # Allow manual trigger

jobs:
  report:
    name: Generate Weekly Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup project
        uses: ./.github/actions/setup-project
        with:
          node-version: '20'
          install-system-deps: 'true'  # Need python3 for some dependencies

      - name: Generate function index
        run: node dist/cli.js --root ./src

      - name: Generate report
        run: |
          node dist/cli.js report \
            --format markdown \
            --output weekly-report.md

      - name: Create issue with report
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('weekly-report.md', 'utf8');

            const date = new Date().toISOString().split('T')[0];
            const title = `📊 Weekly Code Quality Report - ${date}`;

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: report,
              labels: ['code-quality', 'report']
            });

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: weekly-report-${{ github.run_id }}
          path: |
            weekly-report.md
            .function-indexer/index.jsonl